// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4xFSMkNMp7c1h1rChksOMLDiGHWngW74',
    appId: '1:817150869695:web:68131f35dc2972e42c460a',
    messagingSenderId: '817150869695',
    projectId: 'recipein-app',
    authDomain: 'recipein-app.firebaseapp.com',
    storageBucket: 'recipein-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq68P2Ndc47eYoJDkJFuhro5WsbXLwVww',
    appId: '1:817150869695:android:ffb3339d135986bd2c460a',
    messagingSenderId: '817150869695',
    projectId: 'recipein-app',
    storageBucket: 'recipein-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTOZyn7H2LUxRZGwXfkDIjdluWoVaFDXg',
    appId: '1:817150869695:ios:80dd3ae0b5235c292c460a',
    messagingSenderId: '817150869695',
    projectId: 'recipein-app',
    storageBucket: 'recipein-app.firebasestorage.app',
    iosBundleId: 'com.example.recipeinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTOZyn7H2LUxRZGwXfkDIjdluWoVaFDXg',
    appId: '1:817150869695:ios:80dd3ae0b5235c292c460a',
    messagingSenderId: '817150869695',
    projectId: 'recipein-app',
    storageBucket: 'recipein-app.firebasestorage.app',
    iosBundleId: 'com.example.recipeinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4xFSMkNMp7c1h1rChksOMLDiGHWngW74',
    appId: '1:817150869695:web:fb3fa83531cdbebb2c460a',
    messagingSenderId: '817150869695',
    projectId: 'recipein-app',
    authDomain: 'recipein-app.firebaseapp.com',
    storageBucket: 'recipein-app.firebasestorage.app',
  );

}